// Writes db/seed.sql from content/projects/*.md (run by `pnpm db:seed:local`).
// The markdown files are the seed source; D1 is what the site reads.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PROJECT_GROUPS, PROJECT_STATUSES } from "../../../packages/shared/src/types.ts";
import { parseFrontmatter } from "../src/lib/frontmatter.ts";

const contentDir = fileURLToPath(new URL("../content/projects", import.meta.url));
const outFile = fileURLToPath(new URL("../db/seed.sql", import.meta.url));

function fail(slug: string, message: string): never {
  throw new Error(`content/projects/${slug}.md: ${message}`);
}

function text(value: unknown): string | null {
  return typeof value === "string" && value !== "" ? value : null;
}

function sql(value: string | number | null): string {
  if (value === null) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${value.replaceAll("'", "''")}'`;
}

const columns = [
  "slug",
  "title",
  "tagline",
  "summary",
  "body",
  "tech",
  '"group"',
  "status",
  "status_label",
  "sort_order",
  "github_url",
  "live_url",
  "published",
  "source",
];

const rows = readdirSync(contentDir)
  .filter((name) => name.endsWith(".md"))
  .sort()
  .map((name) => {
    const slug = name.replace(/\.md$/, "");
    const { data, content } = parseFrontmatter(readFileSync(`${contentDir}/${name}`, "utf8"));
    const order = Number(data.order);
    if (!Number.isFinite(order)) fail(slug, '"order" must be a number');
    const title = text(data.title) ?? fail(slug, '"title" is required');
    const summary = text(data.summary) ?? fail(slug, '"summary" is required');
    const tagline = text(data.tagline) ?? fail(slug, '"tagline" is required');
    const group = text(data.group);
    if (!group || !(PROJECT_GROUPS as readonly string[]).includes(group)) {
      fail(slug, `"group" must be one of ${PROJECT_GROUPS.join(", ")}`);
    }
    const status = text(data.status);
    if (!status || !(PROJECT_STATUSES as readonly string[]).includes(status)) {
      fail(slug, `"status" must be one of ${PROJECT_STATUSES.join(", ")}`);
    }
    const tech = Array.isArray(data.tech) ? data.tech : [];
    return [
      slug,
      title,
      tagline,
      summary,
      content,
      JSON.stringify(tech),
      group,
      status,
      text(data.statusLabel),
      order,
      text(data.github),
      text(data.live),
      1,
      "seed",
    ]
      .map(sql)
      .join(", ");
  });

// Re-running is safe: a row is only overwritten while it is still an untouched
// seed row (source = 'seed'), and `published` is left as it is.
const updates = columns
  .filter((column) => !["slug", "published", "source"].includes(column))
  .map((column) => `  ${column} = excluded.${column}`);

const statements = rows.map(
  (values) =>
    `INSERT INTO projects (${columns.join(", ")})\nVALUES (${values})\nON CONFLICT (slug) DO UPDATE SET\n${updates.join(",\n")},\n  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')\nWHERE projects.source = 'seed';`,
);

mkdirSync(fileURLToPath(new URL("../db", import.meta.url)), { recursive: true });
writeFileSync(
  outFile,
  `-- Generated by scripts/seed-projects.ts from content/projects/*.md. Do not edit.\n${statements.join("\n\n")}\n`,
);
console.log(`db/seed.sql: ${rows.length} projects`);
